# Generated by Django 3.0.5 on 2021-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('department', models.IntegerField(blank=True, choices=[(1, '営業部'), (2, '総務部'), (3, '製造部')], null=True, verbose_name='所属部署')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
            ],
        ),
    ]
